// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZzWfLoOxoC1dJGmd59nbOEvFugHw-bvM',
    appId: '1:471455626735:web:4c5d82088122b745fb321a',
    messagingSenderId: '471455626735',
    projectId: 'flutter-firebase-64f0b',
    authDomain: 'flutter-firebase-64f0b.firebaseapp.com',
    storageBucket: 'flutter-firebase-64f0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE4otM7bdHTBce4eUYG6qT0w3998-FMsk',
    appId: '1:471455626735:android:d973e1d8e4c06fb5fb321a',
    messagingSenderId: '471455626735',
    projectId: 'flutter-firebase-64f0b',
    storageBucket: 'flutter-firebase-64f0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC390pDlUh8jGubBOjmMN5WmNRQ21N_k08',
    appId: '1:471455626735:ios:8d3ecb9c54d6b82afb321a',
    messagingSenderId: '471455626735',
    projectId: 'flutter-firebase-64f0b',
    storageBucket: 'flutter-firebase-64f0b.appspot.com',
    iosBundleId: 'com.example.ff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC390pDlUh8jGubBOjmMN5WmNRQ21N_k08',
    appId: '1:471455626735:ios:d7550724ca315e73fb321a',
    messagingSenderId: '471455626735',
    projectId: 'flutter-firebase-64f0b',
    storageBucket: 'flutter-firebase-64f0b.appspot.com',
    iosBundleId: 'com.example.ff.RunnerTests',
  );
}
